name: Check docker image

on:
  schedule:
    - cron: '0 0 * * *'

jobs:
  docker-sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Check if update available
        id: check
        uses: lucacome/docker-image-update-checker@v1
        with:
          base-image: ubuntu:22.04
          image: fxti/google-repo-tool:latest

      - name: Login to DockerHub
        if: steps.check.outputs.needs-updating == 'true'
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        if: steps.check.outputs.needs-updating == 'true'
        uses: docker/build-push-action@v5
        with:
          context: sync
          push: true
          tags: fxti/google-repo-tool:latest

      - name: Feishu Notification
        if: steps.check.outputs.needs-updating == 'true'
        run: |
          curl -X POST -H "Content-Type: application/json" -d '{"msg_type":"text","content":{"text":"docker-sync image has been updated"}}' ${{ secrets.FEISHU_BOT_WEBHOOK }}

  docker-mirror:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Check if update available
        id: check
        uses: lucacome/docker-image-update-checker@v1
        with:
          base-image: alpine:latest
          image: fxti/git-daemon:latest

      - name: Login to DockerHub
        if: steps.check.outputs.needs-updating == 'true'
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        if: steps.check.outputs.needs-updating == 'true'
        uses: docker/build-push-action@v5
        with:
          context: mirror
          push: true
          tags: fxti/git-daemon:latest

      - name: Feishu Notification
        if: steps.check.outputs.needs-updating == 'true'
        run: |
          curl -X POST -H "Content-Type: application/json" -d '{"msg_type":"text","content":{"text":"docker-mirror image has been updated"}}' ${{ secrets.FEISHU_BOT_WEBHOOK }}

  frps-latest:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Generate Dockerfile
        run: |
          cd ./frps
          chmod +x generate-dockerfile.sh
          ./generate-dockerfile.sh
          cat ./Dockerfile

      - name: Build check
        uses: docker/build-push-action@v5
        with:
          context: frps
          tags: fxti/frps-latest:latest

      - uses: stefanzweifel/git-auto-commit-action@v5
        id: check-and-commit
        with:
          repository: frps
          commit_message: Apply version bump to frps image

      - name: Login to DockerHub
        if: steps.check-and-commit.outputs.changes_detected == 'true'
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        if: steps.check-and-commit.outputs.changes_detected == 'true'
        uses: docker/build-push-action@v5
        with:
          context: frps
          push: true
          tags: fxti/frps-latest:latest

      - name: Feishu Notification
        if: steps.check-and-commit.outputs.changes_detected == 'true'
        run: |
          curl -X POST -H "Content-Type: application/json" -d '{"msg_type":"text","content":{"text":"frps-latest image has been updated"}}' ${{ secrets.FEISHU_BOT_WEBHOOK }}
